Copy files from gcp-platform-image and Add GitHub Actions workflow to build and publish image
GRIPHONEinc/platform-phpredmin pull request #1
Opened 2021-07-20 10:23 UTC by hitsumabushi845

2021-07-20 12:59 UTC, hitsumabushi845 commented
prod へ IAM 作成してからさしかえる

2021-07-21 13:33 UTC, cstoku commented
https://github.com/GRIPHONEinc/phpredmin/commit/a438132ea2e5d3e06e04076fdf5813454e41d788

2021-08-05 13:08 UTC, hitsumabushi845 commented
repository secret に作成した GSA のキーを設定したので、ワークフローを修正して draft 解除

2021-08-12 03:48 UTC, cstoku requested changes

2021-08-12 03:48 UTC, cstoku commented on config.dist.php
> +return $config;
改行消し飛んでる・・・？
（不要な差分？）

2021-08-12 07:53 UTC, cstoku commented
a

2021-08-12 08:05 UTC, hitsumabushi845 commented
@cstoku

2021-08-12 10:19 UTC, cstoku approved these changes
LGTM:+1:

2021-08-12 10:50 UTC, merged